config/routes.rb
Rails.application.routes.draw do

  # get 'home/index'
  # #devise_for :users
root :to => "home#index"

resources :products
  devise_for :users do
  get 'logout' => 'devise/sessions#destroy'
  end
  require 'sidekiq/web'
mount Sidekiq::Web => '/sidekiq'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
	 validates :name, presence: :true
	 validates :name, uniqueness: { case_sensitive: false }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    #binding.pry
    conditions = ""

    if params[:product]
    params[:product].each do |k,v|
      conditions  = "#{k} like '%#{v}%' " unless v.empty? 
      #b#inding.pry
      #conditions << conditions + 'and'  if !conditions[0].blank? || !conditions[conditions.length-1].blank?
    end
    end
    # binding.pry
    conditions = nil || conditions
    
    #binding.pry
  	 @products = Product.where(conditions).order(params[:sort]).paginate(:page => params[:page], :per_page => 2)
    #binding.pry
    respond_to do |format|
      format.js 
      format.html 
    end
  end

  def new
  	@product=Product.new  	
  end

  def create
  	@product = Product.new(product_params) 
  	if @product.save
  		ProductMailer.with(product: @product).new_product_email.deliver_now
  		ProductWorker.perform_async(@product)
  		flash[:notice] = "yes"
  		redirect_to products_path
  	else
  		flash[:error] = 'No'
  		render new_product_path
  	end
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def update
  	binding.pry
  	@product = Product.find_by(params[:id]) 
  	if @product.update(product_params)
  		ProductMailer.with(product: @product).new_product_email.deliver_now
  		ProductWorker.perform_async(@product)
  		flash[:notice] = "yes"
  		redirect_to products_path
  	else
  		flash[:error] = 'No'
  		render :edit
  	end
  end

  def show
  	@product = Product.find(params[:id])
  end

  private

  def product_params
  	   params.require(:product).permit(:name, :price, :description, :manufacture_year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/home/index.html.erb
	
	<div class='btn-default'><%=link_to 'Add new Product', new_product_path%></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>  
<p class="navbar-text float-right">

</p>
<body>
<%= render 'shared/header' %>
 <%= yield %>
<%= render 'shared/footer' %>
   
  </body>
</html>

app/views/products/_filters.html.erb
<%test= params[:controller].classify.constantize.column_names%>

<%=simple_form_for :product , url: products_path , method: :get,remote: true, input_html: { class: 'default_class' } do |f|%>
<tr>

<%test.each do |a|%>
<th>
<%=f.input "#{a}", label: false, wrapper_html: { class: 'options' }%>

<%= f.submit  "ddd" ,as: :hidden, style:"display: none"%>
</th>


<%end%>
</tr>

<%end%>

app/views/products/_form.html.erb
<div class="container">
	<div class="row">
	
		<%=simple_form_for @product do |f|%>
		<fieldset>
		<%=f.input :name %>
		<%=f.input :price%>
		<%=f.input :description%>
		<%=f.input :manufacture_year,class: 'form-control datepicker'%>
		<%=f.button :submit %>
		</fieldset>
		<%end%>
		
	</div>
</div>

app/views/products/_product.html.erb
<%test= params[:controller].classify.constantize.column_names%>
<%@product = product%>
<tr>
<%test.each do |t|%>
<td><%=product[t]%></td>
<%end%>
<td><%=link_to 'Edit', edit_product_path(product.id)%></td>
<td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %></td>
</tr>

app/views/products/edit.html.erb
<%= @product.errors.full_messages.first if @product.errors.any? %>

<%=render "form"%>

app/views/products/index.html.erb
<%test= params[:controller].classify.constantize.column_names%>


<div class="container">
<div class="row">
<table class="table table-stripped">
<thead>
	<tr>
	<%test.each do |t|%>

	<th><%=t%><div class="btn-group-vertical">
            <a href='products?sort=<%=t%> desc' class="btn btn-xs btn-link p-0">
                <i class="fas fa-sort"></i>
            </a>
            </div></th>
	<%end%>
		</tr>
		</thead>
		
		<%=render partial: "filters"%>
		<tbody id="product_form">
		<%=render @products%>	
		</tbody>
		
	</table>
	</div>
	</div>
	
<div class="digg_pagination">
<%= will_paginate @products, renderer: BootstrapPagination::Rails, previous_label: 'Older', next_label: 'Newer' %>
</div>

app/views/products/index.js.erb
<%#binding.pry%>
$('#product_form').html("<%= escape_javascript(render(@products).html_safe)  %>");

app/views/products/new.html.erb
<%= @product.errors.full_messages.first if @product.errors.any? %>

<%=render "form"%>

app/views/products/show.html.erb
<%test= params[:controller].classify.constantize.column_names%>
<div class="table-responsive-md">
	<table class="table">
	<tr>
	<%data=(0..test.length-1).map{|x| "#{test[x]} "} %>
	<th><%=data.join(",").gsub(',', '')%></th>
		</tr>
		<tr>
			<%data1=(0..test.length-1).collect{|x| @product[test[x]]}%>
			<td><%=data1.join(",").gsub(',', '')%></td>
		</tr>
		
	</table>
	<div><%=link_to "Back", products_path%></div>
</div>

app/views/shared/_footer.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
</div>
      
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    

app/views/shared/_header.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Ram Application</h5>
<nav class="my- my-md-0 mr-md-1">
      <a class="p-2 text-dark" href="#">Features</a>
      </nav>
      <nav class="my-2 my-md-0 mr-md-3">
        <a class="p-2 text-dark" href="#">Features</a>
        <a class="p-2 text-dark" href="#">Enterprise</a>
        <a class="p-2 text-dark" href="#">Support</a>
        <a class="p-2 text-dark" href="#">Pricing</a>
      </nav>
      
      
    <% if user_signed_in? %>
        Signed in as: <%= current_user.email %>
        <%= link_to 'Sign out', destroy_user_session_path, :method => 'delete'  %>
    <% else %>
        <%= link_to 'Register', new_user_registration_path %> or <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
    </div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>